// <auto-generated />
namespace ControlTienda.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FirstSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "202007282225201_FirstSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
